FROM golang:1.20 as builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /build

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

COPY main.go main.go

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -trimpath -o app main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder --chown=nonroot:nonroot /build/app .
USER 65532:65532

ENTRYPOINT ["/app"]